### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by joshferns** [tue-robotics/node_alive#12] opened 2020-11-27 11:11 UTC
I'm attempting migration to ROS Noetic, using Python3
getting the error:

> Traceback (most recent call last):
>   File "/home/ubuntu/catkin_ws/src/node_alive/src/node_alive_server", line 163, in <module>
>     server.loop()
>   File "/home/ubuntu/catkin_ws/src/node_alive/src/node_alive_server", line 148, in loop
>     self.update_nodes()
>   File "/home/ubuntu/catkin_ws/src/node_alive/src/node_alive_server", line 91, in update_nodes
>     ping_nodes = self.re_ping_node.findall(out)
> TypeError: cannot use a string pattern on a bytes-like object

The Error goes away  if  line 35 is changed to 
>     re_ping_node = re.compile(b'pinging ([^ ]+) with a timeout of \d+.\d+s\s*xmlrpc reply from')

ie "b" appended before the pattern

but this ruins the formatting of the response  on line 88, so data gets incorrectly parsed and node remains empty.

**Comment by MatthijsBurgh** [comment] 2020-11-27 11:44
Could `2to3` fix this?

**Comment by Vicidel** [comment] 2020-11-30 13:51
I have the exact same issue, also noetic/python3

I tried using python2.7 to run, but couldn't due to some other python2/3 errors

**Comment by LoyVanBeek** [comment] 2020-11-30 14:29
I think the issue is with `https://docs.python.org/3.6/library/subprocess.html#subprocess.Popen.communicate` that

> returns a tuple `(stdout_data, stderr_data)`. The data will be strings if streams were opened in text mode; otherwise, bytes.

The exception is `TypeError: cannot use a string pattern on a bytes-like object` so we just need to make sure the stream is opened in text mode (since text is what we want to parse). 

https://docs.python.org/3.6/library/subprocess.html#frequently-used-arguments mentions how to do just that:

> If encoding or errors are specified, or universal_newlines is true, the file objects stdin, stdout and stderr will be opened in text mode using the encoding and errors specified in the call or the defaults for io.TextIOWrapper.

I don't have the time to set up my environment with py3 and check the change and make a PR from this, but with the info above, maybe any of you could? Should be straightforward I expect.

**Comment by joshferns** [comment] 2020-12-01 12:35
Hi, the issue is resolved by adding .decode() in line 91

> ping_nodes = self.re_ping_node.findall(out.decode())

if someone else can verify please let me know.

**Comment by MatthijsBurgh** [comment] 2020-12-01 14:04
@joshferns does this work in Python2 too?

**Comment by joshferns** [comment] 2020-12-09 05:47
@MatthijsBurgh  I am not sure, I have already migrated to Python3, (ubuntu 20.04 I dont have python 2 setup).

If possible I will test and report back.

**Comment by MatthijsBurgh** [comment] 2021-01-15 17:05
@joshferns @Vicidel I have made some updates on the `update` branch. It uses the python API of `rosnode` instead of the command line API. Therefore it should be python3 compatible.

**Comment by MatthijsBurgh** [comment] 2021-02-02 21:00
Fixed by #14

**Closed as completed by MatthijsBurgh** 2021-02-02 21:00 UTC
